
var guide ={
Blacktalon: {
    name: "Blacktalon",
    mapg: "Hidden Cave in ein_fild01 / Thanatos Tower (Boss Floor)",
    f1 : "Skogul, Frus, Aliot, Imp, Sniper Cecil, <strong>Ygnizem Cenia</strong>",
    f2 : "Skeggiold, Kasa, Lord Knight Seyren, Majoruros, Sword Guardian, <strong>Ygnezim Cenia</strong>",
    f3 : "Hell Fly, Hellion Revenant, Bio Mobs (LK, Sniper, HW, HP), Salamander, <strong>Detale</strong>",
    mvp : "<strong>Blacktalon</strong> + Kasa, Salamander",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #C0C0C0;'>Immaterial</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #0000ff;'>Crystal</span>, <span style='color: #996600;'>Stone</span>",
    gear : "GTB shield",
    general : "<ul><li>When spawning, rush up towards the narrow walkway up the stairs. If you can't make it, don't drag a mob towards your party</li><li>Floor 1-3 map is a bit annoying because of the hidden pathway so proceed with caution.</li></ul>",
    champion : "<ul><li>Bring a few Green Potions, they'd help to counter confusion when you're setting up at the boss floor</li><li>At F1-F3, clear the middle area first before going deep in the walkways. This will allow your party to group up in an area in case of emergency</li><li>Group up as much Hell Flies and Hellion Revenants as you can to save time</li><li>Make Blacktalon spawns an LP a few cells below where you will be tanking it so your sniper can be positioned there safely without dying from Meteor Storm</li><ul>",
    paladin : "<ul><li>Position correctly during MvP floor. Make sure Blacktalon isn't facing your party</li></ul>",
    sniper : "<ul><li>Bring Ktullanux Armor and your Falcon (for detecting BT).</li><li>Double Strafe from outside of Earthquake range at Blacktalon floor</li></ul>",
    hpriest : "",
    hwizard : "<ul><li>Make sure you have Ice Wall and Ice Wall the narrow path where the party will head to after spawn.</li><li>Don't SG much on F1, it's better for monsters to not be frozen on that floor for snipers to clear faster.</li><li>If you're planning to SG on Blacktalon floor, make sure you are positioned away from the party as you wouldn't want the Kasa and Salamander heading to towards them</li></ul>",
    creator : "<ul><li>Be wary and focus on AD'ing Cecils and Seyren</li></ul>",
    prof : "",
},
Boreas: {
    name : "Boreas",
    mapg : "Ant Hell 1 / Abyss Lake 3",
    f1 : "Hunter Fly, False Angel, Ancient Mummy, Lord of Death, Stormy Knight",
    f2 : "Hunter Fly, Sword Guardian, Agav, Ancient Mummy, Baroness of Retribution, Drake, Stormy Knight, Lord of Death",
    f3 : "Hunter Fly, Assassin Cross Eremes, Sniper Cecil, Byorgue, Gloom Under Night, Amon Ra, Valkyrie Randgris",
    mvp : "Boreas + Thanatos mobs",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #C0C0C0;'>Immaterial</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #ff0000;'>Fire</span>, <span style='color: #996600;'>Stone</span>",
    gear : "GTB shield, Marc armor",
    general : "<ul><li>Stay in the circle when spawning.</li></ul>",
    champion : "<ul><li>Bring Bathory Armor to tank Amon Ra</li><li>Perma-GTB on Boss floor (it dispels).</li><li>One of Boreas slave's (the Dolor), sucks away SP, ask snipers to kill it if they can</li></ul>",
    paladin : "",
    sniper : "<ul><li>Double Strafe from out of Earthquake range at Boss floor</li></ul>",
    hpriest : "",
    hwizard : "",
    creator : "",
    prof : "",
},
Seiren: {
    name : "Seiren",
    mapg : "Abyss Lake 3 / Thanatos Tower",
    f1 : "Howard, Whitesmith Howard (Miniboss), Penomena, Ice Titan, <strong>Garm</strong>",
    f2 : "Katrinn, High Wizard Katrinn (Miniboss), Thanatos Dolor, Ghost Incarnation of Morroc, Ghostring, <strong>Evil Snake Lord</strong>, <strong>Gloom Under Night</strong>",
    f3 : "Magaletha, High Priest Magaletha (Miniboss), Gold Acidus, Angeling, Arc Angeling, False Angel, <strong>Valkyrie Randgris</strong>",
    mvp : "<strong>Seiren</strong> + Raggler, Raydric, Lord Knight Seyren (Miniboss)",
    arrow : "All elements",
    gear : "GTB shield, Medusa shield",
    general : "<ul><li>Seiren will summon LKs whenever the other slaves die! So pay attention when targeting and avoid killing any slave!</li></ul>",
    champion : "<ul><li>Having a <span style='color: #76ae0a;'>Wind</span> RSX and a Holy Armor (for Randgris only) would be lovely</li></ul>",
    paladin : "",
    sniper : "<ul><li>Bring a lot of arrows/quivers and in all elements cause Seiren changes property a lot, and always pay attention to Monster Property and your damage.</li><li>Take of your falcon and normal attack Seiren from out of Earthquake range.</li><li>Easy arrow guide, F1: <span style='color: #76ae0a;'>Wind</span>, F2: <span style='color: #C0C0C0;'>Immaterial</span>, F3: <span style='color: #708090;'>Shadow</span></li></ul>",
    hpriest : "<ul><li>On the Boss Floor, one HP stay off screen preferably, and focus on buffing snipers</li></ul>",
    hwizard : "<ul><li>Get a Marduk Mid if you own one and use it on the Boss floor (Seiren silences a lot)</li><li><strong>Do not cast any magic</strong> other than Quagmire on the Boss floor.</li><li>Monster Property often especially when you see the property change animation on Seiren or your snipers starting to miss.</li></ul>",
    creator : "<ul><li>Help to get rid of Seiren's slave LK as quickly as possible</li></ul>",
    prof : "",
},
Howl: {
    name : "Howl",
    mapg : "Rachel Sanctuary 5 / PVP map",
    f1 : "Rata, Anubis, Abysmal Knight, Elder, Duneyrr, <strong>Amon Ra</strong>, <strong>Incantation Samurai</strong>, <strong>General Egnigem Cenia</strong>, <strong>Orc Hero</strong>",
    f2 : "Wild Rose, Hillslion, Dolomedes, Cornus, Centipede, <strong>Atroce</strong>, <strong>Gopinich</strong>, <strong>Vesper</strong>, <strong>Ktullanux</strong>",
    f3 : "Hydrolancer, Blue Acidus, Gold Acidus, Mutant Dragon, Centipede, Dark <span style='color: #708090;'>Shadow</span>, <strong>Nidhoggr's <span style='color: #708090;'>Shadow</span></strong>",
    mvp : "<strong>Howl</strong> + Ice Titan, Salamander, Tatacho",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #0000ff;'>Crystal</span>, <span style='color: #ff0000;'>Fire</span>, <span style='color: #76ae0a;'>Wind</span>, <span style='color: #996600;'>Stone</span>",
    gear : "GTB shield, Medusa shield, Marc armor",
    general : "<ul><li>Map is super big and annoying, if your party is reliable enough, try splitting on the first and second floor<./li></ul>",
    champion : "<ul><li>Always on GTB for Niddhogr and Howl</li><li>Howl sucks SP, it's recommended to bring Yggdrasil Seed to get SP when you need to urgently re-Steel Body.</li></ul>",
    paladin : "<ul><li>Bring and use an Osiris accessory if you own one.</li><li>Pay attention to your health and the screen. One spiral pierce towards the Champion will kill you. Ask for resu immediately and re-devo as quickly as possible</li></ul>",
    sniper : "<ul><li>DS or auto crit from out of Earthquake range on Boss Floor</li><li>Stick with the other snipers and do not go attacking in your own corner or you'll be a pain in the ass to High Priests.</li><li>When Howl starts a long cast in his first form, STOP ATTACKING immediately or it'll change aggro, and will wipe parts of your party.</li></ul>",
    hpriest : "<ul><li>Two things are crucial during Boss floor: Pneuma and Paladin</li><li>Ask your snipers to stick together under one pneuma, and another pneuma on your party.</li><li>Pay attention to Paladin's health at all time, even if it's full, he can die in a matter of seconds. Always be ready to resurrect him.</li></ul>",
    hwizard : "",
    creator : "<ul><li></li></ul>",
    prof : "",
},
Shiris: {
    name : "Shiris",
    mapg : "Biolabs 3 / Pyramid First Floor",
    f1 : "Grand Peco, Mistress, <strong>Lady Tanee</strong>, <strong>Bacsojin</strong>, <strong>Maya</strong>",
    f2 : "Petite, Blue Acidus, Salamander, Cecil, Magaletha, Banshee Master",
    f3 : "Easy mobs (Rocker, Lunatic, Thief Bug, etc), <strong>High Priest Magaletha</strong>, <strong>Sniper Cecil</strong>",
    mvp : "<strong>Shiris</strong> + Pecos (turns to Hell Flies)",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #C0C0C0;'>Immaterial</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #0000ff;'>Crystal</span>, <span style='color: #76ae0a;'>Wind</span>, <span style='color: #996600;'>Stone</span>",
    gear : "GTB shield, Medusa shield, Marc armor",
    general : "<ul><li>An additional Asura champ (with Osiris) is also great to clear F1-F2 faster.</li></ul>",
    champion : "<ul><li>Run a hybrid Asura/Steel Body build if you can. And help Asura on F1 and F2</li><li><span style='color: #76ae0a;'>Wind</span> RSX is good overall on this GMC. But also do bring <span style='color: #ff0000;'>Fire</span> as you'll need it too for F2 (or in case things break your armor).</li><li>When tanking Shiris make sure she's facing a long wall. Else she will High Jump when attacked, and changes her aggro.</li></ul>",
    paladin : "<ul><li>Pot pot pot</li></ul>",
    sniper : "<ul><li>Bring a Marc armor (for Shiris) and crit stuffs (regular Cecil and MvP have high flee).</li><li>Also bring a lot of <span style='color: #996600;'>Stone</span> Arrows</li><li>Auto attack from afar with <span style='color: #996600;'>Stone</span> Arrow (if your HW is constantly JT'ing Shiris).</li></ul>",
    hpriest : "<ul><li>A <span style='color: #76ae0a;'>Wind</span> Marc is great on Boss Floor. Else you might want to take off your Deviling too to tank the Lord of Vermillion.</li><li>Split jobs if there's a few of you when killing the Bio 3 MvPs</li></ul>",
    hwizard : "<ul><li>Make sure you have Ice Wall in case the party wants to ledge.</li><li>High Vit or Orc Hero mid helps a lot too when ledging</li><li>Help with Safety Wall for the Bio3 MvPs, and make sure that the MvPs always get quagmired!</li><li>Jupitel Thunder all the time on Shiris (even if you miss), to help Snipers kill easier,</li></ul>",
    creator : "<ul><li>Don't be stingy with ADs on F1-F3, but also don't dumbly waste too. A completed run is better than a failed run, and AD'ing might help a lot in some cases. If you care too much about the cost, you better just go play other classes :v</li></ul>",
    prof : "",
},
Muui: {
    name : "Muui",
    mapg : "Geffen Dungeon 1 / Geffen Dungeon 4",
    f1 : "Gold Acidus, Banshee, Frus, Deviling, Valkyrie (mini)",
    f2 : "Biolabs mobs (WS, Sniper, HW, LK), Dimik, <strong>Baphomet</strong>, <strong>Vesper</strong>",
    f3 : "Sword Guardian, Archdam, High Wizard Katrinn, Deviling, <strong>Baphomet</strong>, <strong>Gloom Under Night</strong>",
    mvp : "<strong>Muui</strong> + Dark Illusion, Bloody Knight",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #C0C0C0;'>Immaterial</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #0000ff;'>Crystal</span>, <span style='color: #76ae0a;'>Wind</span>, <span style='color: #996600;'>Stone</span>",
    gear : "GTB shield, Medusa shield",
    general : "<ul><li>When spawning head to the corner wall on the left hand side.</li></ul>",
    champion : "<ul><li><span style='color: #76ae0a;'>Wind</span> RSX is great here too, but remember to swap to <span style='color: #ff0000;'>Fire</span> RSX agaisnt Gloom.</li><li>When tanking Muui, make sure to position him against a wall in a way that your position and his lines up perpendicularly to a wall. He has backslide, and he won't be able to backslide when too close to a wall!</li><li><span style='color: #76ae0a;'>Wind</span> Armor + Alice for Muui</li></ul>",
    paladin : "<ul><li>Run Osiris accessory and pay attention to your hp. Muui spirals, so one spiral might take you out. Ask for resu asap.</li></ul>",
    sniper : "<ul><li>Auto attack from inside party with <span style='color: #fc3;'>Silver</span> arrow.</ul></li>",
    hpriest : "<ul><li>Pay attention to Paladin's hp. If they die, resu as quickly as possible</li><li>If Muui is facing your party, Pneuma is crucial. Else you can also ask the party to be positioned away so that no one would die from it's breath attack.</li></ul>",
    hwizard : "<ul><li>Don't Storm Gust on the first floor, Snipers would be able to handle the monsters much easier if you don't</li><li>Quag, Amp and SG the heck out of third floor</ul></ul>",
    creator : "<ul><li>AD the Bio3 mobs and Sword Guardians heading towards the party</li></ul>",
    prof : "",
},
Sushi: {
    name : "Sushi",
    mapg : "Thanatos / PVP map",
    f1 : "Ragged Zombie, Loli Ruri, Rata, Duneyrr, Necromancer, <strong>Dark Lord</strong>, <strong>Baphomet</strong>",
    f2 : "Zakudam, Thanatos mobs, <strong>Thanatos</strong>",
    f3 : "Incarnation of Morrocs (all 4), Assassin Cross Eremes, <strong>Thanatos</strong>",
    mvp : "<strong>Sushi</strong> + Biolabs mobs",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #C0C0C0;'>Immaterial</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #ff0000;'>Fire</span>",
    gear : "GTB shield",
    general : "<ul><li>When spawning head north towards the corner.</li></ul>",
    champion : "<ul><li>Bring a lot of Fly Wings in case you get exiled a lot.</li><li>Sushi casts Tarot, so funky stuffs such as dispel even when you have GTB on, and coma might happen. Pay attention to it.</li></ul>",
    paladin : "",
    sniper : "<ul><li>Auto attack from out of Earthquake range with <span style='color: #fc3;'>Silver</span> arrow.</li></ul>",
    hpriest : "<ul><li>Cast Safety Walls all around the party when spawning.</li><li>Thanatos expulse a lot, be careful and try not to tank the damage and dying in vain if you don't think you can take it.</li></ul>",
    hwizard : "",
    creator : "<ul><li>AD and get rid of Sushi's LK slave as quickly as possible.</li></ul>",
    prof : "",
},
Gemini: {
    name : "Gemini",
    mapg : "Brasilis Dungeon 1 / PVP map",
    f1 : "Uzhas, Medusa, Gemini-S58, Seaweed, Sedora, Bow Guardian, High Priest Magaletha, Paladin Randel, <strong>Queen Scaraba</strong>, <strong>Boitata</strong>, <strong>Tendrilion</strong>",
    f2 : "Engkanto, Nepenthis, Tatacho, Naga, Seaweed, Sropho, Bow Guardian, Lord Knight Seyren, High Wizard Katrinn, <strong>Hardrock Mammoth</strong>, <strong>Detale</strong>, <strong>Buwaya</strong>",
    f3 : "Ancient Tree, Strouf, King Dramoh, Seaweed, Tikbalang, Bow Guardian, Stalker Gertie, Professor Celia, Lord Knight Seyren, <strong>Gloom Under Night</strong>, <strong>Leak</strong>, <strong>Kraken</strong>",
    mvp : "<strong>Gemini</strong> + Dame of Sentinel, Garden Watcher",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #C0C0C0;'>Immaterial</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #0000ff;'>Crystal</span>, <span style='color: #ff0000;'>Fire</span>, <span style='color: #76ae0a;'>Wind</span>, <span style='color: #996600;'>Stone</span>",
    gear : "GTB shield, Medusa Shield, Marc Armor ",
    general : "<ul><li>Bring a Professor to dispel defender from Paladin Randel, and Gemini.</li><li>Try to move upwards from spawn towards the wall, and get Ice Walled in.</li></ul>",
    champion : "<ul><li>97 Int or Nightmare Mid or Pet.</li><li>Bring a bit more than usual Fly Wings due to how mobby the map can be, and Gemini MvP also has Expulsion skill.</li><li>Be on GTB against Gemini (Dispel & Earthquake).</li><li>Be careful of Bio4 Professor's Dispel too.</li><li>Greenpot to counter Confusion</li></ul>",
    paladin : "<ul><li>Do your job</li></ul>",
    sniper : "<ul><li>Snipeshoot when it's mobby.</li><li>Focus on Bio4 Paladin, and Bio3 Lord Knight. They're a much bigger threat to the party than some MvPs.</li><li>Bring a looot of Green Pots or run as close to as 97 vit as possible because there's a lot of status effect for this particular GMC.</li><li>Drop some traps near the spawn point after clearing a floor so that the Party can have a bit more time to get ready for the next floor monster spawn</li></ul>",
    hpriest : "<ul><li>There are Bow Guardians in here. It's important to Pneuma the party, but make sure the Pneuma wouldn't prevent Snipers from killing whatever is there in the party.</li><li>Lots of status debuff from MvPs, be ready to Cure Silence, Bless <span style='color: #996600;'>Stone</span> Curse, Recovery Sleep etc your other party mates</li></ul>",
    hwizard : "<ul><li>Quagmire cause it will get very mobby.</li><li>The temptation to cast LoV is high cause of the present of Water element monsters, but use JT instead.</li><li>Storm Gust the party and the tank (when they stop moving) when it gets too mobby</li></ul>",
    creator : "<ul><li>Focus on Bio3 Lord Knight and Bio4 Paladin</li></ul>",
    prof : "<ul><li>Run 100 Vit, it's ok to run low Int.</li><li>Dispel mainly Bio4 Randel (Autoguard, Defender), and Gemini (Defender). Dispel whatever is Assumptio'd by Bio3 High Priest on F1 too.</li><li>Bring Cobwebs and web things running into party.</li><li>Cast Wall of Fog on Party if they're targeted by Bow Guardians.</li><li>Help with Safety Wall.</li><li>Help supply SP with Soul Change.</li><li>Cast low level Land Protector on GM Floor to protect Snipers from Meteor Storm</li></ul>",
},
Lance: {
    name : "Lance",
    mapg : "Iz_dun03 (Undersea Tunnel F4) / Shrine of Aquarius",
    f1 : "Deep Sea Kukre, Freezer, Deep Sea Obeaune, Deep Sea Strouf, Piranha, Wild Rider, Sedora, Kraken Leg, Gazeti, Plasma, <strong>Bloody Knight (event)</strong>, <strong>Turtle General</strong>, <strong>Buwaya</strong>, <strong>Mutant Coelacanth</strong>, <strong>Tao Gunka</strong>, <strong>Boitata</strong>",
    f2 : "Deep Sea Obeaune, Giant Octopus, Penomena, Pouring, Aqua Elemental, Phylla, Rhyncho, Kraken Leg, Incarnation of Morroc, King Dramoh, Assassin Cross Eremes, Coelacanth, <strong>Bacsojin</strong>, <strong>Bloody Knight(event)</strong>, <strong>Egnigem Cenia</strong>, <strong>Leak</strong>, <strong>Kraken</strong>, <strong>Drake</strong>, <strong>Evil Snake Lord</strong>",
    f3 : "Banshee, Solace, Deep Sea Obeaune, Aqua Elemental, Phylla, Sedora, High Wizard Katrinn, Sniper Cecil, High Priest Magaletha,  <strong>Egnigem Cenia</strong>, <strong> Stalker Gertie</strong>, <strong>Gypsy Trentini</strong>",
    mvp : "<strong>Lance</strong> + Pouring, Phylla, Aqua Elemental, Arinam",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #C0C0C0;'>Immaterial</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #0000ff;'>Crystal</span>, <span style='color: #ff0000;'>Fire</span>, <span style='color: #76ae0a;'>Wind</span>, <span style='color: #996600;'>Stone</span>",
    gear : "GTB shield, Medusa Shield, Marc Armor",
    general : "<ul><li>The map has too many paths, be sure to walk around everywhere;</li><li>Some mobs have a lot of HP (Ancient and Deep Sea), be sure to bring a lot of damage per second;</li><li>Watch out for the modified BK, it can wipe your party very fast.</li></ul>",
    champion : "<ul><li>Be aware of Asura from Bio4 MvPs Champion slaves; don't hesitate to ask for FCP everytime it wears out.</li></ul>",
    paladin : "<ul><li>Be sure to watch your HP all the times, as biolabs 4 mvps have mobs that hurt a lot too</li></ul>",
    sniper : "<ul><li>Bring more GJs than usual;</li><li>Bring Unfrozen armor, preferably on sniping suit. You can bring a nightmare mid for Kraken, too.</li><li>Bring a lot of <span style='color: #76ae0a;'>Wind</span> Arrows.</li></ul>",
    hpriest : "<ul><li>Watch out in Kraken, party needs Pneuma all the time;</li><li>Bring Unfrozen Armor;</li><li>Watch out for biolabs 3 mobs.</li></ul>",
    hwizard : "<ul><li>The temptation to cast LoV is high cause of the present of Water element monsters, only use it in low hp mobs;</li><li>That's the best GMC to use JT in the MvPs;</li><li>Bring more GJ than usual;</li><li>Switch to full support in some biolabs MvPs.</li></ul>",
    creator : "<ul><li>Bring a lot of coats.</li><li>Bring a lot of AD sets (at least 500) to finish this GMC fast. AD works well against Biolabs and Malangdo (Deep Sea) mobs.</li><li>Acid Demonstration is a decent DPS against Lance MvP.</li></ul>",
    prof : "<ul><li>Cast Violent Gale when possible;</li><li>Watch out to LP snipers when BK appears;</li><li>Support the tanker on MvPs;</li><li>Be ready to Soul Change Snipers/HWs when needed;</li></ul>",
},
Saen: {
    name : "Saen",
    mapg : "Scaraba Hole 2 / Event Map",
    f1 : "Tamruan, Miyabi Doll, Tengu, Jing Guai, Green Maiden, Evil Nymph, Executioner, Mysteltainn, Ogretooth, Flamel, Paladin Randel, Lord Knight Seyren, <strong>White Lady</strong>, <strong>Evil Snake Lord</strong>, <strong>Samurai Specter</strong>, <strong>Turtle General</strong>, <strong>Bloody Knight (event)</strong>",
    f2 : "Banshee, Horong, Dark Frame, Evil Druid, Aunoe, Fanat, Incarnation of Morroc, Hellion Revenant, Necromancer, Dark Illusion, Flamel, Seyren, Randel, <strong>Bloody Knight(event)</strong>, <strong>Fallen Bishop Hibram</strong>, <strong>Gloom Under Night</strong>, <strong>Vesper</strong>",
    f3 : "Medusa, Bloody Butterfly, Rata, Aqua Elemental, Engkanto, Harpy, Mavka, Despero/Dolor/Odium of Thanatos, Duneyrr, Flamel, Valkyrie, <strong>Naght Sieger</strong>",
    mvp : "<strong>Saen</strong> + Horong, Incarnation of Satan Morroc",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #C0C0C0;'>Immaterial</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #0000ff;'>Crystal</span>, <span style='color: #ff0000;'>Fire</span>, <span style='color: #76ae0a;'>Wind</span>",
    gear : "GTB shield, Medusa Shield, Marc Armor",
    general : "<ul><li>The map has many paths, be sure to familiarize yourself with the map;</li><li>It has many powerful mobs that can wipe your party, so use caution;</li><li>Especially watch out for the Event BK, it can wipe your party very fast.</li></ul>",
    champion : "<ul><li>Do not use asura strike on Saen's first form, it will retaliate with a full heal. Use Investigate.</li><li>Asura Strike on Saen's third form changes her to Ghost element. Since element change cannot be dispelled, consider using Investigate instead!</li></ul>",
    paladin : "<ul><li>Osiris accessory is suggested here, since you will die a lot;</li><li>Providence is extremely helpful here, since Saen is a demon.</li></ul>",
    sniper : "<ul><li>Bring plenty of <span style='color: #C0C0C0;''><span style='color: #C0C0C0;'>Immaterial</span></span> arrows, so you can kill the Incarnation of Morroc (Ghost) slaves quickly during the Saen fight; These ghosts heal the MVP.</li><li>Bring extra yggdrasil leaf, so that you can res your party if needed.</li><li>Optional: Stand close (wear GTB in pneuma) to respond quickly.</li></ul>",
    hpriest : "<ul><li>Cast safety wall on the party at the start of floors one and two to protect against the Event Bloody Knight.</li><li>Bring a bathory armor if you want to tank Hibram.</li></ul>",
    hwizard : "<ul><li>Make sure you have level 4 or higher ice wall. Ice wall one side of your party before mobs spawn in;</li><li>You can help damage Naght Sieger with Jupitel Thunder.</li><li>On the final floor, stay close to your main tank and spam SW on yourself. If your main tank is exiled/killed, be the immediate tank substitute.</li></ul>",
    creator : "<ul><li>Bring lots of glistening coats, many mobs can break equipment, especially on the first floor. Do not hesitate to FCP everyone on the first floor.</li><li>Acid Demonstration works wonders here, so make sure to bring more than usual (500-700 AD).</li></ul>",
    prof : "<ul><li>Dispel Paladin Randel as soon as you can, it uses defender and autoguard.</li><li>Be ready to tank Saen in the final floor and lure/tank monsters in F1-F3.</li></ul>",
},
Spica: {
    name : "Spica",
    mapg : "ra_san01 / arug_cas03",
    f1 : "Sniper Cecil, Angeling, Necromancer, Wild Rider, Garm Baby, Tamruan, Solace, Pinguicula, <strong>High Priest Magaletha</strong>, <strong>Fallen Bishop Hibram</strong>, <strong>Amon Ra</strong>",
    f2 : "Sniper Cecil, Tatacho, Dark Pinguicula, Arc Angeling, Aliza, Alicel, Chung E, Deleter, <strong>RSX</strong>, <strong>Garm</strong>, <strong>Piamette</strong>, <strong>Stalker Gertie</strong>",
    f3 : "Sniper Cecil, High Priest Magaletha, Skeggiold (Blue), Dolomedes, Tatacho, Cat o' Nine Tails, Observation, Deviling, Shelter, <strong>High Wizard Kathryne</strong>, <strong>Valkyrie Randgris</strong>, <strong>Gioia</strong>",
    mvp : "<strong>Spica</strong> + Tamadora, Gioia",
    arrow : "<span style='color: #fc3;'>Silver</span>, <span style='color: #C0C0C0;'>Immaterial</span>, <span style='color: #708090;'>Shadow</span>, <span style='color: #ff0000;'>Fire</span>, <span style='color: #76ae0a;'>Wind</span>, <span style='color: #996600;'>Stone</span>, Neutral",
    gear : "GTB shield",
    general : "<ul><li> ra_san01 is a large map. Can split up to clear faster as long as you avoid the major MVPs.</li><li> Spica casts EQ over Level 10. Max range Snipers get hit.</li><li> Spica first form starts as Holy. Second form starts as Ghost. Both forms have Elemental Change.</li></ul>",
    champion : "<ul><li> Spica summon Gioia which uses Dispell. Need to be on GTB.</li><li> Spica uses Demonstration, need FCP.</li></ul>",
    sniper : "<ul><li> Zakudam very good in this GMC.</li></ul>",
    hpriest : "<ul><li> Need Pnuma vs Spica. </li><li> Snipers / two handers will still die to EQ so be ready to resurrect. Only happens at low health second form.</li></ul>",
    hwizard : "<ul><li> Good to bring Mistress mid for help with SW against Bio MVP, VR.</li><li> Occasionally AoE Spica to kill Tamadora slaves. Quagmire + JT spam.</li><li> Zakudam good in this GMC.</li></ul>",
    prof : "<ul><li> Dispell and Web good on several mobs.</li><li> Do not use Web on Spica. She will TP.</li><li> Dispell Spica regularly.</li></ul>",
}
}