
var guide ={
Blacktalon: {
    name: "Blacktalon",
    mapg: "Hidden Cave in ein_fild01 / Thanatos Tower (Boss Floor)",
    f1 : "Skogul, Frus, Aliot, Imp, Sniper Cecil, <strong>Ygnizem Cenia</strong>",
    f2 : "Skeggiold, Kasa, Lord Knight Seyren, Majoruros, Sword Guardian, <strong>Ygnezim Cenia</strong>",
    f3 : "Hell Fly, Hellion Revenant, Bio Mobs (LK, Sniper, HW, HP), Salamander, <strong>Detale</strong>",
    mvp : "<strong>Blacktalon</strong> + Kasa, Salamander",
    arrow : "Silver, Immaterial, Shadow, Crystal, Stone",
    gear : "GTB shield",
    general : "<ul><li>When spawning, rush up towards the narrow walkway up the stairs. If you can't make it, don't drag a mob towards your party</li><li>Floor 1-3 map is a bit annoying because of the hidden pathway so proceed with caution.</li></ul>",
    champion : "<ul><li>Bring a few Green Potions, they'd help to counter confusion when you're setting up at the boss floor</li><li>At F1-F3, clear the middle area first before going deep in the walkways. This will allow your party to group up in an area in case of emergency</li><li>Group up as much Hell Flies and Hellion Revenants as you can to save time</li><li>Make Blacktalon spawns an LP a few cells below where you will be tanking it so your sniper can be positioned there safely without dying from Meteor Storm</li><ul>",
    paladin : "<ul><li>Position correctly during MvP floor. Make sure Blacktalon isn't facing your party</li></ul>",
    sniper : "<ul><li>Bring Ktullanux Armor and your Falcon (for detecting BT).</li><li>Double Strafe from outside of Earthquake range at Blacktalon floor</li></ul>",
    hpriest : "",
    hwizard : "<ul><li>Make sure you have Ice Wall and Ice Wall the narrow path where the party will head to after spawn.</li><li>Don't SG much on F1, it's better for monsters to not be frozen on that floor for snipers to clear faster.</li><li>If you're planning to SG on Blacktalon floor, make sure you are positioned away from the party as you wouldn't want the Kasa and Salamander heading to towards them</li></ul>",
    creator : "<ul><li>Be wary and focus on AD'ing Cecils and Seyren</li></ul>",
    prof : "",
},
Boreas: {
    name : "Boreas",
    mapg : "Ant Hell 1 / Abyss Lake 3",
    f1 : "Hunter Fly, False Angel, Ancient Mummy, Lord of Death, Stormy Knight",
    f2 : "Hunter Fly, Sword Guardian, Agav, Ancient Mummy, Baroness of Retribution, Drake, Stormy Knight, Lord of Death",
    f3 : "Hunter Fly, Assassin Cross Eremes, Sniper Cecil, Byorgue, Gloom Under Night, Amon Ra, Valkyrie Randgris",
    mvp : "Boreas + Thanatos mobs",
    arrow : "Silver, Immaterial, Shadow, Fire, Stone",
    gear : "GTB shield, Marc armor",
    general : "<ul><li>Stay in the circle when spawning.</li></ul>",
    champion : "<ul><li>Bring Bathory Armor to tank Amon Ra</li><li>Perma-GTB on Boss floor (it dispels).</li><li>One of Boreas slave's (the Dolor), sucks away SP, ask snipers to kill it if they can</li></ul>",
    paladin : "",
    sniper : "<ul><li>Double Strafe from out of Earthquake range at Boss floor</li></ul>",
    hpriest : "",
    hwizard : "",
    creator : "",
    prof : "",
},
Seiren: {
    name : "Seiren",
    mapg : "Abyss Lake 3 / Thanatos Tower",
    f1 : "Howard, Whitesmith Howard (Miniboss), Penomena, Ice Titan, <strong>Garm</strong>",
    f2 : "Katrinn, High Wizard Katrinn (Miniboss), Thanatos Dolor, Ghost Incarnation of Morroc, Ghostring, <strong>Evil Snake Lord</strong>, <strong>Gloom Under Night</strong>",
    f3 : "Magaletha, High Priest Magaletha (Miniboss), Gold Acidus, Angeling, Arc Angeling, False Angel, <strong>Valkyrie Randgris</strong>",
    mvp : "<strong>Seiren</strong> + Raggler, Raydric, Lord Knight Seyren (Miniboss)",
    arrow : "All elements",
    gear : "GTB shield, Medusa shield",
    general : "<ul><li>Seiren will summon LKs whenever the other slaves die! So pay attention when targeting and avoid killing any slave!</li></ul>",
    champion : "<ul><li>Having a Wind RSX and a Holy Armor (for Randgris only) would be lovely</li></ul>",
    paladin : "",
    sniper : "<ul><li>Bring a lot of arrows/quivers and in all elements cause Seiren changes property a lot, and always pay attention to Monster Property and your damage.</li><li>Take of your falcon and normal attack Seiren from out of Earthquake range.</li><li>Easy arrow guide, F1: Wind, F2: Immaterial, F3: Shadow</li></ul>",
    hpriest : "<ul><li>On the Boss Floor, one HP stay off screen preferably, and focus on buffing snipers</li></ul>",
    hwizard : "<ul><li>Get a Marduk Mid if you own one and use it on the Boss floor (Seiren silences a lot)</li><li><strong>Do not cast any magic</strong> other than Quagmire on the Boss floor.</li><li>Monster Property often especially when you see the property change animation on Seiren or your snipers starting to miss.</li></ul>",
    creator : "<ul><li>Help to get rid of Seiren's slave LK as quickly as possible</li></ul>",
    prof : "",
},
Howl: {
    name : "Howl",
    mapg : "Rachel Sanctuary 5 / PVP map",
    f1 : "Rata, Anubis, Abysmal Knight, Elder, Duneyrr, <strong>Amon Ra</strong>, <strong>Incantation Samurai</strong>, <strong>General Egnigem Cenia</strong>, <strong>Orc Hero</strong>",
    f2 : "Wild Rose, Hillslion, Dolomedes, Cornus, Centipede, <strong>Atroce</strong>, <strong>Gopinich</strong>, <strong>Vesper</strong>, <strong>Ktullanux</strong>",
    f3 : "Hydrolancer, Blue Acidus, Gold Acidus, Mutant Dragon, Centipede, Dark Shadow, <strong>Nidhoggr's Shadow</strong>",
    mvp : "<strong>Howl</strong> + Ice Titan, Salamander, Tatacho",
    arrow : "Silver, Shadow, Crystal, Fire, Wind, Stone",
    gear : "GTB shield, Medusa shield, Marc armor",
    general : "<ul><li>Map is super big and annoying, if your party is reliable enough, try splitting on the first and second floor<./li></ul>",
    champion : "<ul><li>Always on GTB for Niddhogr and Howl</li><li>Howl sucks SP, it's recommended to bring Yggdrasil Seed to get SP when you need to urgently re-Steel Body.</li></ul>",
    paladin : "<ul><li>Bring and use an Osiris accessory if you own one.</li><li>Pay attention to your health and the screen. One spiral pierce towards the Champion will kill you. Ask for resu immediately and re-devo as quickly as possible</li></ul>",
    sniper : "<ul><li>DS or auto crit from out of Earthquake range on Boss Floor</li><li>Stick with the other snipers and do not go attacking in your own corner or you'll be a pain in the ass to High Priests.</li><li>When Howl starts a long cast in his first form, STOP ATTACKING immediately or it'll change aggro, and will wipe parts of your party.</li></ul>",
    hpriest : "<ul><li>Two things are crucial during Boss floor: Pneuma and Paladin</li><li>Ask your snipers to stick together under one pneuma, and another pneuma on your party.</li><li>Pay attention to Paladin's health at all time, even if it's full, he can die in a matter of seconds. Always be ready to resurrect him.</li></ul>",
    hwizard : "",
    creator : "<ul><li></li></ul>",
    prof : "",
},
Shiris: {
    name : "Shiris",
    mapg : "Biolabs 3 / Pyramid First Floor",
    f1 : "Grand Peco, Mistress, <strong>Lady Tanee</strong>, <strong>Bacsojin</strong>, <strong>Maya</strong>",
    f2 : "Petite, Blue Acidus, Salamander, Cecil, Magaletha, Banshee Master",
    f3 : "Easy mobs (Rocker, Lunatic, Thief Bug, etc), <strong>High Priest Magaletha</strong>, <strong>Sniper Cecil</strong>",
    mvp : "<strong>Shiris</strong> + Pecos (turns to Hell Flies)",
    arrow : "Silver, Immaterial, Shadow, Crystal, Wind, Stone",
    gear : "GTB shield, Medusa shield, Marc armor",
    general : "<ul><li>An additional Asura champ (with Osiris) is also great to clear F1-F2 faster.</li></ul>",
    champion : "<ul><li>Run a hybrid Asura/Steel Body build if you can. And help Asura on F1 and F2</li><li>Wind RSX is good overall on this GMC. But also do bring Fire as you'll need it too for F2 (or in case things break your armor).</li><li>When tanking Shiris make sure she's facing a long wall. Else she will High Jump when attacked, and changes her aggro.</li></ul>",
    paladin : "<ul><li>Pot pot pot</li></ul>",
    sniper : "<ul><li>Bring a Marc armor (for Shiris) and crit stuffs (regular Cecil and MvP have high flee).</li><li>Also bring a lot of Stone Arrows</li><li>Auto attack from afar with Stone Arrow (if your HW is constantly JT'ing Shiris).</li></ul>",
    hpriest : "<ul><li>A Wind Marc is great on Boss Floor. Else you might want to take off your Deviling too to tank the Lord of Vermillion.</li><li>Split jobs if there's a few of you when killing the Bio 3 MvPs</li></ul>",
    hwizard : "<ul><li>Make sure you have Ice Wall in case the party wants to ledge.</li><li>High Vit or Orc Hero mid helps a lot too when ledging</li><li>Help with Safety Wall for the Bio3 MvPs, and make sure that the MvPs always get quagmired!</li><li>Jupitel Thunder all the time on Shiris (even if you miss), to help Snipers kill easier,</li></ul>",
    creator : "<ul><li>Don't be stingy with ADs on F1-F3, but also don't dumbly waste too. A completed run is better than a failed run, and AD'ing might help a lot in some cases. If you care too much about the cost, you better just go play other classes :v</li></ul>",
    prof : "",
},
Muui: {
    name : "Muui",
    mapg : "Geffen Dungeon 1 / Geffen Dungeon 4",
    f1 : "Gold Acidus, Banshee, Frus, Deviling, Valkyrie (mini)",
    f2 : "Biolabs mobs (WS, Sniper, HW, LK), Dimik, <strong>Baphomet</strong>, <strong>Vesper</strong>",
    f3 : "Sword Guardian, Archdam, High Wizard Katrinn, Deviling, <strong>Baphomet</strong>, <strong>Gloom Under Night</strong>",
    mvp : "<strong>Muui</strong> + Dark Illusion, Bloody Knight",
    arrow : "Silver, Immaterial, Shadow, Crystal, Wind, Stone",
    gear : "GTB shield, Medusa shield",
    general : "<ul><li>When spawning head to the corner wall on the left hand side.</li></ul>",
    champion : "<ul><li>Wind RSX is great here too, but remember to swap to Fire RSX agaisnt Gloom.</li><li>When tanking Muui, make sure to position him against a wall in a way that your position and his lines up perpendicularly to a wall. He has backslide, and he won't be able to backslide when too close to a wall!</li><li>Wind Armor + Alice for Muui</li></ul>",
    paladin : "<ul><li>Run Osiris accessory and pay attention to your hp. Muui spirals, so one spiral might take you out. Ask for resu asap.</li></ul>",
    sniper : "<ul><li>Auto attack from inside party with Silver arrow.</ul></li>",
    hpriest : "<ul><li>Pay attention to Paladin's hp. If they die, resu as quickly as possible</li><li>If Muui is facing your party, Pneuma is crucial. Else you can also ask the party to be positioned away so that no one would die from it's breath attack.</li></ul>",
    hwizard : "<ul><li>Don't Storm Gust on the first floor, Snipers would be able to handle the monsters much easier if you don't</li><li>Quag, Amp and SG the heck out of third floor</ul></ul>",
    creator : "<ul><li>AD the Bio3 mobs and Sword Guardians heading towards the party</li></ul>",
    prof : "",
},
Sushi: {
    name : "Sushi",
    mapg : "Thanatos / PVP map",
    f1 : "Ragged Zombie, Loli Ruri, Rata, Duneyrr, Necromancer, <strong>Dark Lord</strong>, <strong>Baphomet</strong>",
    f2 : "Zakudam, Thanatos mobs, <strong>Thanatos</strong>",
    f3 : "Incarnation of Morrocs (all 4), Assassin Cross Eremes, <strong>Thanatos</strong>",
    mvp : "<strong>Sushi</strong> + Biolabs mobs",
    arrow : "Silver, Immaterial, Shadow, Fire",
    gear : "GTB shield",
    general : "<ul><li>When spawning head north towards the corner.</li></ul>",
    champion : "<ul><li>Bring a lot of Fly Wings in case you get exiled a lot.</li><li>Sushi casts Tarot, so funky stuffs such as dispel even when you have GTB on, and coma might happen. Pay attention to it.</li></ul>",
    paladin : "",
    sniper : "<ul><li>Auto attack from out of Earthquake range with Silver arrow.</li></ul>",
    hpriest : "<ul><li>Cast Safety Walls all around the party when spawning.</li><li>Thanatos expulse a lot, be careful and try not to tank the damage and dying in vain if you don't think you can take it.</li></ul>",
    hwizard : "",
    creator : "<ul><li>AD and get rid of Sushi's LK slave as quickly as possible.</li></ul>",
    prof : "",
},
Gemini: {
    name : "Gemini",
    mapg : "Brasilis Dungeon 1 / PVP map",
    f1 : "Uzhas, Medusa, Gemini-S58, Seaweed, Sedora, Bow Guardian, High Priest Magaletha, Paladin Randel, <strong>Queen Scaraba</strong>, <strong>Boitata</strong>, <strong>Tendrilion</strong>",
    f2 : "Engkanto, Nepenthis, Tatacho, Naga, Seaweed, Sropho, Bow Guardian, Lord Knight Seyren, High Wizard Katrinn, <strong>Hardrock Mammoth</strong>, <strong>Detale</strong>, <strong>Buwaya</strong>",
    f3 : "Ancient Tree, Strouf, King Dramoh, Seaweed, Tikbalang, Bow Guardian, Stalker Gertie, Professor Celia, Lord Knight Seyren, <strong>Gloom Under Night</strong>, <strong>Leak</strong>, <strong>Kraken</strong>",
    mvp : "<strong>Gemini</strong> + Dame of Sentinel, Garden Watcher",
    arrow : "Silver, Immaterial, Shadow, Crystal, Fire, Wind, Stone",
    gear : "GTB shield, Medusa Shield, Marc Armor ",
    general : "<ul><li>Bring a Professor to dispel defender from Paladin Randel, and Gemini.</li><li>Try to move upwards from spawn towards the wall, and get Ice Walled in.</li></ul>",
    champion : "<ul><li>97 Int or Nightmare Mid or Pet.</li><li>Bring a bit more than usual Fly Wings due to how mobby the map can be, and Gemini MvP also has Expulsion skill.</li><li>Be on GTB against Gemini (Dispel & Earthquake).</li><li>Be careful of Bio4 Professor's Dispel too.</li><li>Greenpot to counter Confusion</li></ul>",
    paladin : "<ul><li>Do your job</li></ul>",
    sniper : "<ul><li>Snipeshoot when it's mobby.</li><li>Focus on Bio4 Paladin, and Bio3 Lord Knight. They're a much bigger threat to the party than some MvPs.</li><li>Bring a looot of Green Pots or run as close to as 97 vit as possible because there's a lot of status effect for this particular GMC.</li><li>Drop some traps near the spawn point after clearing a floor so that the Party can have a bit more time to get ready for the next floor monster spawn</li></ul>",
    hpriest : "<ul><li>There are Bow Guardians in here. It's important to Pneuma the party, but make sure the Pneuma wouldn't prevent Snipers from killing whatever is there in the party.</li><li>Lots of status debuff from MvPs, be ready to Cure Silence, Bless Stone Curse, Recovery Sleep etc your other party mates</li></ul>",
    hwizard : "<ul><li>Quagmire cause it will get very mobby.</li><li>The temptation to cast LoV is high cause of the present of Water element monsters, but use JT instead.</li><li>Storm Gust the party and the tank (when they stop moving) when it gets too mobby</li></ul>",
    creator : "<ul><li>Focus on Bio3 Lord Knight and Bio4 Paladin</li></ul>",
    prof : "<ul><li>Run 100 Vit, it's ok to run low Int.</li><li>Dispel mainly Bio4 Randel (Autoguard, Defender), and Gemini (Defender). Dispel whatever is Assumptio'd by Bio3 High Priest on F1 too.</li><li>Bring Cobwebs and web things running into party.</li><li>Cast Wall of Fog on Party if they're targeted by Bow Guardians.</li><li>Help with Safety Wall.</li><li>Help supply SP with Soul Change.</li><li>Cast low level Land Protector on GM Floor to protect Snipers from Meteor Storm</li></ul>",
}
}